#  If a dimension property has a hierarchical code list with a parentChildProperty then the value of that dimension property on every observation must be reachable from a root of hierarchy using zero or more hops along the parentChildProperty links.

ASK {
    ?obs qb:dataSet/qb:structure/qb:component/qb:componentProperty ?dim .
    ?dim a qb:DimensionProperty ;
        qb:codeList ?list .
    ?list a qb:HierarchicalCodeList .
    ?obs ?dim ?v .
    FILTER NOT EXISTS { ?list qb:hierarchyRoot/(^eg:parent)* ?v }
}
