#  If a dimension property has a qb:codeList, then the value of the dimension property on every observation must be in the code list
#  Case of skos:Collection

ASK {
    ?obs qb:dataSet/qb:structure/qb:component/qb:componentProperty ?dim .
    ?dim a qb:DimensionProperty ;
        qb:codeList ?list .
    ?list a skos:Collection .
    ?obs ?dim ?v .
    FILTER NOT EXISTS { ?list skos:member+ ?v }
}
